name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
         with:
  github_user_name: mauree155
  svg_out_path: dist/github-contribution-grid-snake.svg
  background_color: '#0d1117'
  color_snake: '#8b0000'
  color_dots: '#444c56,#2f363d,#1c2128,#0d1117'


      - name: Commit and push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch
          git switch output || git checkout -b output
          cp -r dist/* .
          git add . --force
          git commit -m "Generate contribution snake" || echo "No changes to commit"
          git push origin output
